###
POST http://localhost:4000/register
Content-Type: application/json

{   
    "email" : "jake@jake",
    "password" : "jake",
    "firstName" : "jadk",
    "lastName" : "rith",
    "bio" : "TEST BIO"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "jake@jake",
    "password" : "jake"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAamFrZSIsInBhc3N3b3JkIjoiamFrZSIsImlhdCI6MTYwNTgzMzg0NSwiZXhwIjoxNjA4NDI1ODQ1fQ.63fEbGWCzdBTGnH0DR7666Bft9HQFIiszuV7voXQ3jo"
}

###
GET http://localhost:4000/getApplicationUser/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAamFrZSIsInBhc3N3b3JkIjoiamFrZSIsImlhdCI6MTYwNTgzMzcwNSwiZXhwIjoxNjA1ODM1NTA1fQ.fLnsimLg4gGkxi7BXjrWmIS7Hv8kFdEyyegUhiIjjIE

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAamFrZSIsInBhc3N3b3JkIjoiamFrZSIsImlhdCI6MTYwNTgzNDA1MSwiZXhwIjoxNjA4NDI2MDUxfQ.i17W2me7Jg-9yzZvRqt-mUBk8d3NHLpwEJf_M87V4go"
}