###
POST http://localhost:4000/register
Content-Type: application/json

{   
    "email" : "jake@jake",
    "password" : "jake",
    "firstName" : "jadk",
    "lastName" : "rith",
    "bio" : "TEST BIO"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "jake@jake",
    "password" : "jake"
}

###
GET http://localhost:4000/getApplicationUser/1